#!/usr/bin/env bash
# Installs nginx server
sudo apt-get update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'

#Configure your Nginx to have custom 404 page

echo "Hello World!" | sudo tee /var/www/html/index.html
string_for_replacement="server_name crysart.tech www.crysart.tech;\n\trewrite ^\/redirect_me https:\/\/www.google.com permanent;"
sudo sed -i "s/server_name _;/$string_for_replacement/" /etc/nginx/sites-enabled/default*

# code to create error page and add a redirect for error 404
echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html
string_for_replacement="server_name crysart.tech www.crysart.tech;\n\n\terror_page 404 \/404.html;\n"
sudo sed -i "s/server_name crysart.tech www.crysart.tech;/$string_for_replacement/" /etc/nginx/sites-enabled/default*

# add new costom header
string_for_replacement="try_files \$uri \$uri\/ =404;\n\n\t\tadd_header X-Served-By \$hostname;"
sudo sed -i "s/try_files \$uri \$uri\/ =404;/$string_for_replacement/" /etc/nginx/sites-enabled/default*

# restart the server
sudo service nginx start
