#!/usr/bin/env bash
# Create a script to install and configure HAProxy on lb-01 server
# Install and configure HAproxy on my lb-01 server.

sudo apt-get -y update
sudo apt-get -y install haproxy

# edit config file
server_config=\
"
frontend  crysart-frontend
        bind *:80
	mode http
	default_backend crysart-backend
backend crysart-backend
	balance roundrobin
        server 94251-web-01 3.89.155.51:80  check
	server 94251-web-02 100.26.169.4:80  check
"
echo "$server_config" | sudo tee -a /etc/haproxy/haproxy.cfg

# enable haproxy to be started by init script

echo "ENABLED=1" | sudo tee -a /etc/default/haproxy

sudo service haproxy restart
